src/Entity/AlbumRoots.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

#[ApiResource]
#[ORM\Entity(repositoryClass: \App\Repository\AlbumRootsRepository::class)]
#[ORM\Table(name: 'AlbumRoots')]
class AlbumRoots extends BaseEntity implements \Stringable
{
    public function __construct()
    {
        $this->albums = new ArrayCollection();
    }
    #[ORM\OneToMany(targetEntity: \App\Entity\Albums::class, mappedBy: 'albumRoot')]
    private $albums;
    /**
     * @return Collection|Albums[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }
    /**
     * @return AlbumRoots
     */
    public function setAlbums(mixed $albums)
    {
        $this->albums = $albums;
        return $this;
    }
    #[ORM\Column(type: 'integer', name: 'id')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private $id;
    public function getId() { return $this->id; }
    #[ORM\Column(type: 'text', name: 'label')]
    private $label;
    public function getLabel() { return $this->label; }
    #[ORM\Column(type: 'integer', name: 'status')]
    private $status;
    public function getStatus() { return $this->status; }
    #[ORM\Column(type: 'integer', name: 'type')]
    private $type;
    public function getType() { return $this->type; }
    #[ORM\Column(type: 'text', name: 'identifier')]
    private $identifier;
    public function getIdentifier() { return $this->identifier; }
    #[ORM\Column(type: 'text', name: 'specificPath')]
    private $specificPath;
    public function getSpecificpath() { return $this->specificPath; }
    public function __toString(): string
    {
          return $this->getSpecificpath();
    }
    public function getUniqueIdentifiers() {
        return [
            'albumRootId' => $this->getId()
        ];
    }
}

src/Entity/Albums.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

#[ApiResource]
#[ORM\Entity(repositoryClass: \App\Repository\AlbumsRepository::class)]
#[ORM\Table(name: 'Albums')]
class Albums extends BaseEntity implements \Stringable
{
    public function __construct()
    {
        $this->images = new ArrayCollection();
    }
    #[ORM\Column(type: 'integer', name: 'id')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private $id;
    public function getId() { return $this->id; }
    #[ORM\ManyToOne(targetEntity: \App\Entity\AlbumRoots::class, inversedBy: 'albums')]
    #[ORM\JoinColumn(name: 'albumroot')]
    private $albumRoot;
    public function getAlbumroot(): AlbumRoots { return $this->albumRoot; }
    #[ORM\OneToMany(targetEntity: \App\Entity\Image::class, mappedBy: 'album', fetch: 'EAGER')]
    private $images;
    public function getImages() { return $this->images; }
    #[ORM\Column(type: 'string', name: 'relativePath')]
    private $relativePath;
    public function getRelativepath() { return $this->relativePath; }
    public function getPath() { return $this->getAlbumroot()->getSpecificpath() . $this->relativePath; }
    #[ORM\Column(type: 'date', name: 'date')]
    private $date;
    public function getDate() { return $this->date; }
    #[ORM\Column(type: 'string', name: 'caption')]
    private $caption;
    public function getCaption() { return $this->caption; }
    #[ORM\Column(type: 'text', name: 'collection')]
    private $collection;
    public function getCollection() { return $this->collection; }
    #[ORM\Column(type: 'integer', name: 'icon')]
    private $icon;
    public function getIcon() { return $this->icon; }
    public function __toString(): string
    {
          return $this->getAlbumroot() . $this->getRelativepath();
    }
    public function getUniqueIdentifiers() {
        return [
            'albumId' => $this->getId()
        ];
    }
}

src/Entity/Image.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: \App\Repository\ImageRepository::class)]
#[ORM\Table(name: 'Images')]
class Image extends BaseEntity implements \Stringable
{
    public function __construct()
    {
        $this->tags = new ArrayCollection();
        $this->subjects = new ArrayCollection();
        $this->objects = new ArrayCollection();
    }
    #[ORM\Column(type: 'integer', name: 'id')]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private $id;
    public function getId()
    {
        return $this->id;
    }
    #[ORM\ManyToOne(targetEntity: \App\Entity\Albums::class, inversedBy: 'images')]
    #[ORM\JoinColumn(name: 'album')]
    private $album;
    #[ORM\ManyToMany(targetEntity: \App\Entity\Tags::class, mappedBy: 'images')]
    #[ORM\JoinTable(name: 'ImageTags', joinColumns: [], inverseJoinColumns: [])]
    #[ORM\JoinColumn(name: 'tagid', referencedColumnName: 'id')]
    #[ORM\JoinColumn(name: 'imageid', referencedColumnName: 'id')]
    private $tags;
    public function getTags()
    {
        return $this->tags;
    }
    #[ORM\OneToOne(targetEntity: \App\Entity\ImageInformation::class, fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'id', referencedColumnName: 'imageid')]
    private $information;
    #[ORM\OneToOne(targetEntity: \App\Entity\ImageMetadata::class, mappedBy: 'image', orphanRemoval: true, fetch: 'EAGER')]
    private $meta = null;
    #[ORM\OneToOne(targetEntity: \App\Entity\ImageHistory::class, fetch: 'EAGER')]
    #[ORM\JoinColumn(name: 'id', referencedColumnName: 'imageid')]
    private $history;
    #[ORM\OneToOne(targetEntity: \App\Entity\ImagePositions::class, mappedBy: 'image', orphanRemoval: true, fetch: 'EAGER')]
    private $location = null;
    /**
     * @return mixed
     */
    public function getLocation()
    {
        return $this->location;
    }
    /**
     * @return Image
     */
    public function setLocation(mixed $location)
    {
        $this->location = $location;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getMeta(): ?ImageMetadata
    {
        return $this->meta;
    }
    /**
     * @param mixed $meta
     * @return Image
     */
    public function setMeta(?ImageMetadata $meta)
    {
        $this->meta = $meta;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getInfo(): ImageInformation
    {
        return $this->information;
    }
    /**
     * @param mixed $information
     * @return Image
     */
    public function setInfo(ImageInformation $information)
    {
        $this->information = $information;
        return $this;
    }
    public function isRaw(): bool
    {
        return $this->getInfo() ? str_starts_with((string) $this->getInfo()->getFormat(), 'RAW') : true;
    }
    public function getAlbum(): ?Albums
    {
        return $this->album;
    }
    #[ORM\Column(type: 'string', name: 'name')]
    private $name;
    public function getName()
    {
        return $this->name;
    }
    #[ORM\Column(type: 'integer', name: 'status')]
    private $status;
    public function getStatus()
    {
        return $this->status;
    }
    #[ORM\Column(type: 'integer', name: 'category')]
    private $category;
    public function getCategory()
    {
        return $this->category;
    }
    #[ORM\Column(type: 'datetime', name: 'modificationDate')]
    private $modificationDate;
    public function getModificationdate()
    {
        return $this->modificationDate;
    }
    #[ORM\Column(type: 'integer', name: 'fileSize')]
    private $fileSize;
    public function getFilesize()
    {
        return $this->fileSize;
    }
    #[ORM\Column(type: 'text', name: 'uniqueHash')]
    private $uniqueHash;
    public function getUniquehash()
    {
        return $this->uniqueHash;
    }
    public function __toString(): string
    {
        return sprintf("%d: %s", $this->getId(), $this->name);
    }
    /**
     * @return mixed
     */
    public function getInformation()
    {
        return $this->information;
    }
    /**
     * @return Image
     */
    public function setInformation(mixed $information)
    {
        $this->information = $information;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getImageHistory(): ?ImageHistory
    {
        return $this->history;
    }
    /**
     * @return Image
     */
    public function setHistory(mixed $history)
    {
        $this->history = $history;
        return $this;
    }
    public function getUrlPath()
    {
        return $this->getAlbum() ? sprintf("%s/%s", $this->getAlbum()->getPath(), $this->getName()) : '#';
    }
    public function getFilePath()
    {
        return $this->getAlbum()->getAlbumroot()->getSpecificpath() . '/' . $this->getAlbum()->getRelativepath() . '/' . $this->getName();
    }
    public function getUniqueIdentifiers()
    {
        return [
            'id' => $this->getId()
        ];
    }
    /**
     * @return mixed
     */
    public function getObjects()
    {
        return $this->objects;
    }
    /**
     * @return Image
     */
    public function setObjects(mixed $objects)
    {
        $this->objects = $objects;
        return $this;
    }
    /**
     * @return mixed
     */
    public function getSubjects()
    {
        return $this->subjects;
    }
    /**
     * @return Image
     */
    public function setSubjects(mixed $subjects)
    {
        $this->subjects = $subjects;
        return $this;
    }
}

templates/dk/album.html.twig
{% extends "base.html.twig"  %}

{% block body %}

    <h3>{{ album.images|length }} Images in {{ album }}</h3>

    {% if album.images.count != images|length %}
        <span class="text-danger">Warning: {{ album.images.count - images|length }} images are missing metadata</span>
        {% endif %}

    <table class="table table-condensed dataTables-basic">
        <thead>
        <tr>
            <th>ID/Name</th>
            <th>Widen</th>
            <td>Meta</td>
            <td>Location</td>
            <td>Tags</td>
        </tr>
        </thead>
        <tbody>

        {% for i in album.images %}
            <tr valign="top" >
                <td><a class="btn btn-sm" href="{{ path('dk_image', i.rp) }}">{{ i.id }}</a>
                    <br />
                <a class="btn btn-sm" href="{{ path('dk_image', i.rp) }}">{{ i.name }}</a></td>

                {# square image, needs border?
                <td>
                    {% if i.raw %}
                        RAW
                        {% else %}
                    <img src="{{ asset(i.filePath) | imagine_filter('squared_thumbnail') }}" />
                        {% endif %}
                </td>
                #}
                <td>
                    {% if not i.raw %}
                    {% set thumbUrl = asset(i.urlPath) | imagine_filter('my_widen_filter') %}
                    <a href="{{ thumbUrl }}">
                        <img src="{{ thumbUrl }}" title="{{ thumbUrl }}" />
                    </a>
                        {% endif %}

                </td>

                <td>{{ i.meta  }}</td>
                <td>{{ i.location }}</td>

{#                <td>{{ i.tags|join('<br />')|raw }}</td>#}
                {% if app.request.get('debug', false) %}
                <td>{{ dump(i.meta) }}</td>
                <td>{{ dump(i.info) }}</td>
                <td>{{ dump(i.tags) }}</td>
                <td>{{ dump(i) }}</td>
                    {% endif %}
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/dk/albumRoots.html.twig
{% extends "base.html.twig"  %}

{% block body %}

    <h3>Album Roots</h3>
    icon?
    <i class="fa fa-plus">ICON</i>

    <table class="table table-striped">
        <tbody>

        <h3>{{ albumRoots|length }} AlbumRoots</h3>
        <thead>
        <tr>
            <th>Path</th>
            <th>Status</th>
            <th>Type</th>
            <th>Album#</th>
        </tr>
        </thead>
        <tbody>

        {% for a in albumRoots %}
            <tr>
                <td>
                        <a class="btn btn-info" href="{{ path('dk_album_root', {albumRootId: a.id}) }}">{{ a.specificpath }}</a>
                </td>
                <td>{{ a.status }}</td>
                <td>{{ a.type }}</td>
                <td>{{ a.albums|length }}</td>
                {#
                <td>{{ a.date }}</td>
                <td>{{ a.label }}</td>
                <td>{{ a.caption }}</td>
                <td>{{ a.relativePath }}</td>
                #}
                {% if app.request.get('debug', false) %}
                <td>{{ dump(a) }}</td>
                    {% endif %}
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/dk/albums.html.twig
{% extends "base.html.twig"  %}

{% block body %}

    <h3>{{ albums|length }} albums in Album Root {{ albumRoot }}</h3>
    <table class="table dataTables-basic table-condensed">
        <thead>
        <tr>
            <th>Path</th>
            <th>Date</th>
            <th>Collection</th>
            <th>Caption</th>
            <th>Image Count</th>
        </tr>
        </thead>
        <tbody>
        {% for a in albums %}
            {% if a.images.count > 0 %}
            <tr>
                <td>
                        <a href="{{ path('dk_album', {albumId: a.id}) }}">{{ a.relativePath }}</a>
                </td>
                <td>{{ a.date|date("Y-m-d") }}</td>
                <td>{{ a.collection }}</td>
                <td>{{ a.caption }}</td>
                <td>{{ a.images|length }}</td>
                {% if app.request.get('debug') %}
                <td>{{ dump(a) }}</td>
                    {% endif %}
            </tr>
                {% endif %}
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

templates/dk/image.html.twig
{% extends "base.html.twig"  %}

{% macro attr(attributes) %}
    {% for var, val in attributes %}
        <li>{{ var }}: {{ val }}</li>
        {% endfor %}
    {% endmacro %}


{% macro thumb(image) %}
    {% set filter = 'my_widen_filter' %}
    {% set thumbUrl = image.raw
        ? 'https://dummyimage.com/200x80/000/fff&text=' ~ image.name
        : asset(image.urlPath) | imagine_filter(filter) %}
    <div class="img-thumbnail">
        <a href="{{ path('dk_image', image.rp) }}">
            <b>{{ image }}</b><br />
        </a>


        <a href="{{ thumbUrl }}">
            <img src="{{ thumbUrl }}" title="{{ thumbUrl }}"/>
        </a>

    </div>
{% endmacro %}


{% block body %}
    {% import _self as macro %}

    <h1>Image {{ image }}</h1>

    <h3>THUMB</h3>
    <a href="{{ path('dk_thumb', {id: image.id}) }}">THUMB</a>
    <table class="table">

    <tr>
        {% for filter in ['squared_thumbnail', 'my_heighten_filter', 'my_widen_filter'] if not image.raw%}
            {% set thumbUrl = asset(image.urlPath) | imagine_filter(filter) %}
            <td>
                <b>{{ filter }}</b><br />
                <a href="{{ thumbUrl }}">
                    <img src="{{ thumbUrl }}" title="{{ thumbUrl }}"/>
                </a>

            </td>
        {% endfor %}

    </tr>
    </table>

    {% for relation in ['subjects', 'objects'] %}
    <h3>{{ attribute(image, relation).count }} {{ relation }} Images</h3>
        <ol>
            {% for image in attribute(image, relation) %}
                <li>
                    {{ macro.thumb(image) }}
                </li>
            {% endfor %}

        </ol>

        {% endfor %}


    {% if history %}
        <h3>History for Image {{ image.id }}</h3>
        {% if image.imageHistory %}
            uuid: {{ image.imageHistory.uuid|default('..') }}
        {% else %}
            No History
        {% endif %}

            {% for step in history %}
                {% if step.name == 'file' %}
                    {% set f = step.data %}
                    {% set a = f['@attributes'] %}
                    {% set file = step.data.fileParams['@attributes'] %}
                    <h4>{{ a.type|default('no-type') }} {{ file.fileName|default('~') }}: <small>{{ a.uuid|default('..') }}</small></h4>
                    {% set fileParams = f['fileParams']['@attributes'] %}

                    {% if step.image %}
                        {{ macro.thumb(step.image) }}
                    {% endif %}
                    {{ macro.attr(fileParams) }}
                {% elseif step.name == 'filter' %}
                    {% set f = step.data %}
                    {% set a = f['@attributes'] %}

                    <h4 title="{{ a.filterName }}">{{ a.filterDisplayName }} Filter, v{{ a.filterVersion }}
                        {% if a.branch|default(false) %}<i class="fa fa-code-fork pull-left"></i>{% endif %}
                        <span class="badge">{{ a.filterCategory }}</span>
                    </h4>
                    <ol>
                        {% for param in f.params.param %}
                            {% set p = param['@attributes'] %}
                            <li>
                                {{ p.name }}: {{ p.value }}
                            </li>
                        {% endfor %}
                    </ol>
                {% else %}
                    Invalid Step
                {% endif %}
            {% endfor %}

                {#
            <h3>History, Version {{ image.history['@attributes'].version }}</h3>
            {% set f = image.history.file %}

            <h4>File</h4>

            <h4>Filter</h4>
            {{ dump(image.imageHistory.historyArray) }}
            {{ dump(image.imageHistory) }}
            {{ dump(image.history ) }}
            #}
    {% else %}
        <span class="text-danger">
        No Image history record
            </span>
    {% endif %}



    <h3>ORIG</h3>
    <a href="{{ image.urlPath }}">See Original at {{ image.urlPath }}
    </a>
    {#
    {% set filename = "file://///home/tac/elodie-photos/2017-04-Apr/Virginia/2017-04-28_15-32-37-20170428_113237.jpg" %}
    {% set filename = "%s%s"|format(image.album.albumroot, image.urlPath) %}
    <h3>LIIP</h3>
    <img src="{{ asset(filename) | imagine_filter('squared_thumbnail') }}" />
    <br />{{ filename }}
    <img src="{{ asset(image.urlPath)}}" | />



    {% set imageUrl = path('dk_jpg', image.rP) %}


    <h3>OLD WAY</h3>
    <a href="{{ imageUrl }}" class="btn btn-info">
        <img title="{{ imageUrl }}" src="{{ imageUrl }}" />
    </a>
    {{ imageUrl }}
    #}

    {% if app.request.get('debug', false) %}
    {{ dump(image) }}
        {% endif %}

    <pre>
    {{ image_root }}
        {{ image.album.relativepath }}
        {{ image.album.albumroot }}
        {{ image.urlPath }}
    </pre>


{% endblock %}